In [1]:
import numpy as np

## Base

In [2]:
# Importando a base
from sklearn import datasets
iris = datasets.load_iris()

In [3]:
# Dividindo a base
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(iris.data[:,:2], iris.target, test_size=0.25, random_state=0)

base dividida em 25% teste e 75% treino

# Linear Regression

In [4]:
# Importando
from sklearn.linear_model import LinearRegression

In [5]:
# Instanciando com default
linearR_default = LinearRegression()

In [6]:
# Treinando
linearR_default.fit(x_train, y_train)

LinearRegression()

In [7]:
# Agora com a base testes completa
linearR_predict = linearR_default.predict(x_test)

In [8]:
linearR_predict.round()

array([ 2.,  1., -0.,  2.,  0.,  2., -0.,  1.,  1.,  1.,  2.,  1.,  1.,
        1.,  1., -0.,  1.,  1., -0., -0.,  2.,  2.,  0.,  0.,  1., -0.,
        0.,  1.,  1.,  0.,  2.,  2., -0.,  2.,  2.,  1., -0.,  2.])

In [9]:
linearR_default.coef_

array([-0.27627193,  0.10019835,  0.5715101 ])

In [10]:
# Importando
from sklearn import metrics

In [11]:
linearR_accuracy = metrics.accuracy_score(linearR_predict.round(), y_test)
linearR_accuracy

0.8947368421052632

# LogisticRegression

In [12]:
# Importando
from sklearn.linear_model import LogisticRegression

In [13]:
# Instanciando com default
logisticR_default = LogisticRegression()

In [14]:
# Treinando (como nenhum parametro foi indicado no momento da instancia, um warning avisa sobre alguns parametros que serão utilizados - default)
logisticR_default.fit(x_train, y_train)

LogisticRegression()

In [15]:
# Agora com a base testes completa
logisticR_predict = logisticR_default.predict(x_test)

Como o objetivo não é classificar de forma precisa nesse momento e sim estudar como funciona o método, iremos apenas olhar para o resultado do score para garantir que chegamos à alguma classificação e não está muito discrepante do esperado, ou seja, com score muito baixo:

In [16]:
logisticR_accuracy = metrics.accuracy_score(logisticR_predict, y_test)
logisticR_accuracy

0.9473684210526315

# Decision tree

In [17]:
# Importando
from sklearn.tree import DecisionTreeClassifier

In [18]:
# Instanciando com default
dt_default = DecisionTreeClassifier()

In [19]:
dt_default.fit(x_train, y_train)

DecisionTreeClassifier()

In [20]:
# Agora com a base testes completa
dt_predict = dt_default.predict(x_test)

In [21]:
import matplotlib.pyplot as plt
from sklearn.tree import plot_tree

fig, ax = plt.subplots(figsize=(12, 12))
plot_tree(dt_default, fontsize=10)
plt.show()

<Figure size 1200x1200 with 1 Axes>

In [22]:
dt_accuracy = metrics.accuracy_score(dt_predict, y_test)
dt_accuracy

0.9473684210526315

# Ensemble

## maioria simples (uniform voting)

In [23]:
ensemble_predict = []
for i in range(len(x_test)):
    votes = [0, 0, 0]
    for predict in [dt_predict, logisticR_predict, linearR_predict]:
        votes[int(predict[i].round())] += 1
    ensemble_predict.append(votes.index(max(votes)))

In [24]:
np.array(ensemble_predict) - dt_predict

array([ 0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0])

In [25]:
np.array(ensemble_predict) - logisticR_predict

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
np.array(ensemble_predict) - linearR_predict.round()

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  0.])

In [27]:
metrics.accuracy_score(ensemble_predict, y_test)

0.9473684210526315

In [28]:
(dt_accuracy + logisticR_accuracy + linearR_accuracy) / 3

0.9298245614035087